services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp 1
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:8083
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:8083
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:8084
    ports:
      - "19092:19092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    entrypoint: ["sh", "-c", "exec /app/console"]
    environment:
      KAFKA_BROKERS: "redpanda:9092"
      KAFKA_PROTOBUF_ENABLED: "true"
      KAFKA_PROTOBUF_FILESYSTEM_ENABLED: "true"
      KAFKA_PROTOBUF_FILESYSTEM_PATHS: "/etc/protobuf"
      KAFKA_PROTOBUF_MAPPINGS_0_TOPICNAME: "market-ticks-proto"
      KAFKA_PROTOBUF_MAPPINGS_0_VALUEPROTOTYPE: "finance.MarketTick"
    ports:
      - "8080:8080"
    volumes:
      - ./:/etc/protobuf/
    depends_on:
      - redpanda

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - timescaledb

volumes:
  timescaledb-data:
  grafana-storage:
